feat: support workspaces via git worktrees
update help docs

remove old code, refactor for clarity

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,8 +1,16 @@
 #!/usr/bin/env bash
 
-# Call kiota on all test yaml files
+# Call kiota on all test yaml files and generate result stubs
 
-set -e
+ROOT_DIR="$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &>/dev/null && pwd)"
+tests_dir="./tests"
+results_dir="./tests"
+generate_dir="./out"
+if [[ -n "$WORKSPACE" ]]; then
+  tests_dir="$ROOT_DIR/$WORKSPACE/$tests_dir"
+  results_dir="$ROOT_DIR/$WORKSPACE/$results_dir"
+  generate_dir="$ROOT_DIR/$WORKSPACE/$generate_dir"
+fi
 
 mode="main"
 lang="typescript"
@@ -10,51 +18,49 @@ results_only=0
 
 help() {
   cat << EOF
-Test kiota generation
+Run tests of kiota generation
 
-Usage: test [OPTIONS] [#...]
+Usage: run [OPTIONS] [#...]
 
 Options:
 
-  -n, --name <number>   number/name/id of the test to create
-                        default: the next number after the last test in tests/
-                                  starts at 1 if there are no tests
+  -m, --mode <mode>     "main" or "pr"
+                        run with the variant of kiota specified by
+                        the "kiota_main" or "kiota_pr" environment variables
+                        default: main
 
-  -t, --tag <tag>       a tag value placed at the top of the test file
-                        can be specified multiple times to add multiple tags
+  -l, --lang <lang>     the language to use when calling kiota
+                        default: typescript
+                        options:
+                          cli
+                          csharp
+                          go
+                          java
+                          php
+                          python
+                          ruby
+                          swift
+                          typescript
 
   -h, --help            show this help message then exit
 
-  -l, --list            list all test files and the URIs within them then exit
-
-  -c, --check           check all test files and exit with error if any tests
-                        have the same set of URIs
-
-  -s, --sort            sorts the given URIs before writing the new test file
-                        in --list and --check mode, sorts each set of URIs
-                        within each test before outputting/checking
-
-  -f, --force           bypass any errors and silence warnings
-                        - if the test file already exists, overwrite it
-                        - if the same URIs are in another test, write the
-                          new test anyway
-                        - if the URIs after being sorted are in another test,
-                          hide the warning
+  -r, --results-only    only generate result stubs without also running kiota
 
 Positional Arguments:
 
-#     a space-separated list of one or more test ids to prepare results for
+#     a space-separated list of one or more test ids to run kiota for
+      defaults to all tests
 
 Environment Variables:
 
-kiota_main
+kiota_main   the path to the kiota binary to call when mode is "main"
 
-kiota_pr
+kiota_pr     the path to the kiota binary to call when mode is "pr"
 
 EOF
 }
 
-parsed_args=$(getopt --name "test" -o hm:l:r -l help,mode:,lang:,results-only -- "$@")
+parsed_args=$(getopt --name "run" -o hm:l:r -l help,mode:,lang:,results-only -- "$@")
 eval set -- "$parsed_args"
 while :; do
   case "$1" in
@@ -90,10 +96,10 @@ done
 
 kiota="$kiota_main"
 if [[ "$mode" == "pr" ]]; then
-  [[ -n "$kiota_pr" ]] || { echo "Error: must define kiota_pr as path to a kiota exe" >&2; exit 1; }
+  [[ -n "$kiota_pr" ]] || { echo "Error: must provide kiota_pr as a path to a kiota exe" >&2; exit 1; }
   kiota="$kiota_pr"
 else
-  [[ -n "$kiota_main" ]] || { echo "Error: must define kiota_main as path to a kiota exe" >&2; exit 1; }
+  [[ -n "$kiota_main" ]] || { echo "Error: must provide kiota_main as a path to a kiota exe" >&2; exit 1; }
 fi
 
 test_paths=()
@@ -101,7 +107,7 @@ if [[ "$#" -gt 0 ]]; then
   for test_name in "$@"; do
     if [[ -n "$test_name" ]]; then
       [[ "$test_name" =~ ^[0-9]+$ ]] || { echo "Error: test name must be a number" >&2; exit 1; }
-      test_path="tests/$test_name.yaml"
+      test_path="$tests_dir/$test_name.yaml"
       [[ -f "$test_path" ]] || { echo "Error: test does not exist: $test_path" >&2; exit 1; }
       test_paths+=("$test_path")
     fi
@@ -109,19 +115,22 @@ if [[ "$#" -gt 0 ]]; then
 else
   while read -r test_path || [[ -n "$test_path" ]]; do
     test_paths+=("$test_path")
-  done < <(find tests/ -type f -regextype posix-extended -regex "tests/[0-9]+\.yaml" | sort -V)
+  done < <(find "$tests_dir" -type f -regextype posix-extended -regex ".*/tests/[0-9]+\.yaml" | sort -V)
 fi
 
 export KIOTA_OFFLINE_ENABLED=true KIOTA_TUTORIAL_ENABLED=false
 
 for test_path in "${test_paths[@]}"; do
   test_file="${test_path##*/}"
-  out_path="out/$mode/$lang/$test_file"
+  out_path="$generate_dir/$mode/$lang/$test_file"
   if [[ "$results_only" -eq 0 ]]; then
-    "$kiota" generate --exclude-backward-compatible --class-name "ApiSdk" --namespace-name "apiSdk" --language "$lang" --clear-cache --clean-output --output "$out_path" --openapi "$test_path"
+    if ! "$kiota" generate --exclude-backward-compatible --class-name "ApiSdk" --namespace-name "apiSdk" --language "$lang" --clear-cache --clean-output --output "$out_path" --openapi "$test_path"; then
+      echo "Error: failed calling $kiota on $test_path" >&2
+      exit 1
+    fi
     find "$out_path" -type f -exec dos2unix -q {} \+
   fi
-  results_path="results/$mode/$lang/${test_file%\.yaml}.md"
+  results_path="$results_dir/$mode/$lang/${test_file%\.yaml}.md"
   new_md5="$(md5sum "$test_path" | cut -d' ' -f1)"
   if [[ -f "$results_path" ]]; then
     old_md5="$(head -n 1 "$results_path" | sed -r 's/<!-- ([^ ]+) -->/\1/g')"
